INSERT INTO tbl_cards (hp, name, info, attack, damage, weak, resistance, retreat, cardNumberInCollection, collectionId, typeId, stageId) VALUES
(40, 'Bulbasaur', 'A strange seed was planted on its back at birth.', 'Tackle', 10, 'Fire', '', 1, 44, 1, 1, 1),
(50, 'Ivysaur', 'When the bulb on its back grows large, it appears to lose the ability to stand on its hind legs.', 'Vine Whip', 30, 'Fire', '', 2, 30, 1, 1, 2),
(80, 'Venusaur', 'The flower on its back catches the sun’s rays and converts them into energy.', 'Solar Beam', 60, 'Fire', '', 4, 15, 1, 1, 3),
(50, 'Charmander', 'Obviously prefers hot places. When it rains, steam is said to spout from the tip of its tail.', 'Ember', 30, 'Water', '', 1, 55, 1, 2, 1),
(80, 'Charmeleon', 'When it swings its burning tail, it raises the temperature around it.', 'Flamethrower', 50, 'Water', '', 2, 32, 1, 2, 2),
(120, 'Charizard', 'Spits fire that is hot enough to melt boulders.', 'Fire Spin', 100, 'Water', '', 3, 4, 1, 2, 3),
(50, 'Squirtle', 'Shoots water at prey while in the water.', 'Bubble', 20, 'Lightning', '', 1, 7, 1, 3, 1),
(80, 'Wartortle', 'Often hides in water to stalk unknowing prey.', 'Water Gun', 40, 'Lightning', '', 2, 48, 1, 3, 2),
(100, 'Blastoise', 'Once it takes aim at its enemy, it fires its water jets with great precision.', 'Hydro Pump', 60, 'Lightning', '', 3, 2, 1, 3, 3),
(40, 'Pikachu', 'When several of these Pokémon gather, their electricity could build and cause lightning storms.', 'Thunder Shock', 20, 'Fighting', '', 1, 25, 1, 4, 1),
(60, 'Raichu', 'Its tail discharges electricity into the ground, protecting it from getting shocked.', 'Thunderbolt', 80, 'Fighting', '', 2, 26, 1, 4, 2),
(70, 'Jigglypuff', 'Uses its adorable eyes to hypnotize its opponent.', 'Pound', 10, 'Fighting', '', 1, 39, 2, 11, 1),
(90, 'Wigglytuff', 'Has a balloon-like body that can expand effortlessly.', 'Hyper Voice', 50, 'Fighting', '', 2, 40, 2, 11, 2),
(60, 'Meowth', 'Adores round objects and chases shiny things.', 'Scratch', 20, 'Fighting', '', 1, 52, 2, 11, 1),
(80, 'Persian', 'Has a vicious temperament and sharp claws.', 'Slash', 50, 'Fighting', '', 2, 53, 2, 11, 2),
(90, 'Machop', 'Its muscles never grow tired, no matter how much it exercises.', 'Karate Chop', 40, 'Psychic', '', 1, 66, 2, 6, 1),
(100, 'Machoke', 'Its body is incredibly strong, allowing it to carry heavy objects with ease.', 'Submission', 60, 'Psychic', '', 2, 67, 2, 6, 2),
(120, 'Machamp', 'Using its four arms, it delivers punches and chops faster than the eye can follow.', 'Cross Chop', 80, 'Psychic', '', 3, 68, 2, 6, 3),
(80, 'Gastly', 'It is made of gas and can sneak into any space unnoticed.', 'Lick', 30, 'Psychic', '', 1, 92, 2, 5, 1),
(100, 'Haunter', 'It hides in the darkness and terrorizes its victims.', 'Shadow Ball', 40, 'Psychic', '', 2, 93, 2, 5, 2);