INSERT INTO tbl_cards (hp, name, info, attack, damage, weak, resistance, retreat, cardNumberInCollection, collectionId, typeId, stageId) VALUES
(80, 'Gengar', 'Under a full moon, this Pokémon likes to mimic the shadows of people.', 'Night Shade', 50, 'Psychic', '', 3, 94, 2, 5, 3),
(90, 'Onix', 'Burrows at high speeds, creating tunnels underground.', 'Rock Throw', 40, 'Water', '', 3, 95, 2, 6, 1),
(70, 'Eevee', 'Its genetic makeup enables it to evolve into multiple forms.', 'Quick Attack', 20, 'Fighting', '', 1, 133, 2, 11, 1),
(80, 'Vaporeon', 'Its body’s cellular structure is similar to water molecules.', 'Water Gun', 40, 'Lightning', '', 2, 134, 2, 3, 2),
(80, 'Jolteon', 'It accumulates electricity in its fur, discharging it when threatened.', 'Thunder Shock', 50, 'Fighting', '', 2, 135, 2, 4, 2),
(80, 'Flareon', 'Has a flame sac inside its body that constantly burns.', 'Fire Blast', 60, 'Water', '', 2, 136, 2, 2, 2),
(70, 'Dratini', 'Lives in deep, dark water where it constantly grows.', 'Wrap', 20, 'Dragon', '', 1, 147, 3, 10, 1),
(90, 'Dragonair', 'A mystical Pokémon known to change the weather.', 'Dragon Rage', 50, 'Dragon', '', 2, 148, 3, 10, 2),
(120, 'Dragonite', 'It is said to have the intelligence of a human.', 'Hyper Beam', 80, 'Dragon', '', 3, 149, 3, 10, 3),
(70, 'Snorlax', 'Very lazy. It only wakes up to eat.', 'Body Slam', 60, 'Fighting', '', 4, 143, 3, 11, 1),
(80, 'Lapras', 'Has been called the “King of the Seas.”', 'Water Gun', 40, 'Lightning', '', 3, 131, 3, 3, 1),
(70, 'Cubone', 'Wears the skull of its deceased mother.', 'Bone Club', 30, 'Water', '', 1, 104, 3, 6, 1),
(100, 'Marowak', 'Its bone is its primary weapon in battle.', 'Bonemerang', 50, 'Water', '', 2, 105, 3, 6, 2),
(90, 'Electabuzz', 'Feeds on electrical currents.', 'Thunder Punch', 40, 'Fighting', '', 2, 125, 3, 4, 1),
(120, 'Magmar', 'Its body burns like a furnace.', 'Flamethrower', 50, 'Water', '', 2, 126, 3, 2, 1),
(70, 'Hitmonlee', 'Can stretch its legs to launch powerful kicks.', 'Jump Kick', 50, 'Psychic', '', 2, 106, 3, 6, 1),
(70, 'Hitmonchan', 'Punches lightning fast.', 'Jab', 40, 'Psychic', '', 2, 107, 3, 6, 1),
(100, 'Pinsir', 'Uses its powerful pincers to crush foes.', 'Vice Grip', 60, 'Fire', '', 2, 127, 3, 1, 1),
(100, 'Kangaskhan', 'Carries its baby in a pouch.', 'Comet Punch', 50, 'Fighting', '', 2, 115, 3, 11, 1),
(80, 'Tangela', 'Covered in vines it uses for camouflage.', 'Bind', 40, 'Fire', '', 2, 114, 3, 1, 1),
(90, 'Seadra', 'Can swim backwards with agility.', 'Water Gun', 50, 'Lightning', '', 2, 117, 3, 3, 2),
(70, 'Golbat', 'Flies at night in search of prey.', 'Leech Life', 40, 'Psychic', '', 2, 42, 3, 5, 2),
(80, 'Dewgong', 'Uses ice attacks in battle.', 'Aurora Beam', 50, 'Metal', '', 3, 87, 3, 3, 2),
(100, 'Arcanine', 'Runs faster than the wind.', 'Flame Wheel', 80, 'Water', '', 3, 59, 3, 2, 2),
(110, 'Aerodactyl', 'A prehistoric Pokémon revived from a fossil.', 'Wing Attack', 60, 'Metal', '', 3, 142, 3, 11, 1),
(90, 'Zapdos', 'Controls thunder and lightning.', 'Thunderstorm', 80, 'Fighting', '', 3, 145, 3, 4, 1),
(90, 'Moltres', 'A bird Pokémon said to create fire with every wing flap.', 'Fire Spin', 80, 'Water', '', 3, 146, 3, 2, 1),
(100, 'Articuno', 'Said to appear in snowstorms.', 'Ice Beam', 80, 'Metal', '', 3, 144, 3, 3, 1),
(120, 'Mewtwo', 'A genetically engineered Pokémon.', 'Psystrike', 100, 'Psychic', '', 3, 150, 3, 5, 1);