INSERT INTO tbl_cards (hp, name, info, attack, damage, weak, resistance, retreat, cardNumberInCollection, collectionId, typeId, stageId) VALUES
(100, 'Golem', 'Its boulder-like body is incredibly tough.', 'Rock Slide', 80, 'Water', '', 4, 76, 3, 6, 3),
(90, 'Rhydon', 'Its horn can drill through solid rock.', 'Horn Attack', 70, 'Water', '', 3, 112, 3, 6, 2),
(70, 'Lickitung', 'Uses its tongue to sense its surroundings.', 'Lick', 30, 'Fighting', '', 2, 108, 3, 11, 1),
(80, 'Chansey', 'Stores nutrients in its egg.', 'Egg Bomb', 50, 'Fighting', '', 3, 113, 3, 11, 1),
(90, 'Scyther', 'Slashes foes with its sharp scythes.', 'Slash', 60, 'Fire', '', 3, 123, 3, 1, 1),
(100, 'Jynx', 'Has a mysterious, hypnotic dance.', 'Ice Punch', 50, 'Metal', '', 3, 124, 3, 5, 1),
(80, 'Slowpoke', 'Often seen staring blankly at the water.', 'Headbutt', 20, 'Lightning', '', 1, 79, 3, 5, 1),
(90, 'Slowbro', 'Its tail is bitten by a Shellder, triggering evolution.', 'Water Gun', 40, 'Lightning', '', 2, 80, 3, 5, 2),
(100, 'Dodrio', 'Can sprint at high speeds.', 'Tri Attack', 60, 'Fighting', '', 3, 85, 3, 11, 2),
(70, 'Hypno', 'Uses its pendulum to hypnotize foes.', 'Dream Eater', 50, 'Psychic', '', 3, 97, 3, 5, 2),
(80, 'Farfetch’d', 'Uses a leek as its weapon.', 'Fury Cutter', 40, 'Fighting', '', 2, 83, 3, 11, 1),
(70, 'Mr. Mime', 'Uses invisible walls to defend itself.', 'Barrier', 30, 'Psychic', '', 3, 122, 3, 5, 1),
(90, 'Magneton', 'Generates a magnetic field for defense.', 'Thunderbolt', 60, 'Fighting', '', 3, 82, 3, 4, 2),
(100, 'Cloyster', 'Has an extremely hard shell.', 'Spike Cannon', 70, 'Metal', '', 3, 91, 3, 3, 2),
(80, 'Graveler', 'Has a tough, rocky body.', 'Rollout', 40, 'Water', '', 2, 75, 3, 6, 2),
(90, 'Kabuto', 'A prehistoric Pokémon revived from a fossil.', 'Scratch', 30, 'Grass', '', 1, 140, 3, 6, 1),
(100, 'Kabutops', 'Uses its scythe-like arms for hunting.', 'Hydro Cutter', 80, 'Grass', '', 2, 141, 3, 6, 2),
(90, 'Omanyte', 'Revived from an ancient fossil.', 'Water Gun', 40, 'Lightning', '', 1, 138, 3, 3, 1),
(100, 'Omastar', 'Preys on small Pokémon using its tentacles.', 'Spike Cannon', 60, 'Lightning', '', 2, 139, 3, 3, 2),
(80, 'Golduck', 'A fast swimmer with psychic abilities.', 'Confusion', 50, 'Lightning', '', 3, 55, 3, 3, 2),
(70, 'Poliwhirl', 'Its body constantly spins, generating power.', 'Water Gun', 40, 'Lightning', '', 2, 61, 3, 3, 2),
(90, 'Poliwrath', 'Uses its strong arms to deliver punches.', 'Hydro Pump', 80, 'Lightning', '', 3, 62, 3, 3, 3),
(80, 'Kingler', 'Its large claw can crush rocks.', 'Guillotine', 60, 'Lightning', '', 3, 99, 3, 3, 2),
(70, 'Doduo', 'Runs fast to escape predators.', 'Peck', 30, 'Fighting', '', 1, 84, 3, 11, 1),
(80, 'Exeggutor', 'Has multiple heads that each think independently.', 'Stomp', 50, 'Fire', '', 3, 103, 3, 1, 2),
(90, 'Clefable', 'Has a graceful, fairy-like appearance.', 'Metronome', 40, 'Fighting', '', 2, 36, 3, 11, 2),
(90, 'Butterfree', 'Has powdery scales that cause paralysis.', 'Psybeam', 50, 'Fire', '', 3, 12, 3, 1, 2),
(100, 'Beedrill', 'Uses its sharp stingers for fierce attacks.', 'Twineedle', 60, 'Fire', '', 3, 15, 3, 1, 2),
(120, 'Pidgeot', 'Flies at great speeds.', 'Wing Attack', 70, 'Fighting', '', 3, 18, 3, 11, 2);